### ISSUE TITLE
FriendlyName always reports "changed"

### ISSUE THREAD

**Issue by bellackn** [tobias-richter/ansible-tasmota#2]
When you change the `FriendlyName` value of a device, Ansible will always report "changed", no matter if the name is the same as before.

**Comment by tobias-richter** [comment]
There is no logic in the Ansible Role to add the "1" to FriendlyName as tasmota does.
`FriendlyName` is an Tasmota internal abbreviation for `FriendlyName1` so Tasmota will answer with `FriendlyName1` instead of `FriendlyName`.

So just use `FriendlyName1`.

Btw. this also applies to other settings like `NtpServer` or `Rule`

**Comment by tobias-richter** [comment]
@bellackn you are also free to create a PR which adds `1` to the command strings when appropriate.
